name: Chirpr-Automation tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          record: true
          auto-cancel-after-failures: 2

      - name: Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: cypress/artifacts
          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`
